Traceback (most recent call last):
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\daniel.oropeza\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import urllib3
from bs4 import BeautifulSoup
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
from string import punctuation
from collections import defaultdict
import collections
from heapq import nlargest
import unicodedata

http = urllib3.PoolManager()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<module>[1;34m[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib3[39;00m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mbs4[39;00m [38;5;28;01mimport[39;00m BeautifulSoup
[1;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnltk[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtokenize[39;00m [38;5;28;01mimport[39;00m sent_tokenize,word_tokenize
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnltk[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcorpus[39;00m [38;5;28;01mimport[39;00m stopwords
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnltk[39;00m[38;5;21;01m.[39;00m[38;5;21;01mprobability[39;00m [38;5;28;01mimport[39;00m FreqDist

[1;31mModuleNotFoundError[0m: No module named 'nltk'
ModuleNotFoundError: No module named 'nltk'

